
=== Les 3 datasets utilisés

- https://www.kaggle.com/datasets/iamsouravbanerjee/human-development-index-dataset[IDH, GNI CO² par pays par année] 
* Licence utilisée: Creative Commons Attribution 3.0 IGO *(CC BY 3.0 IGO)*

* Obtention des fichiers de données
+
Le dataset est téléchargable sous la forme d'un fichier CSV, il est disponible https://gitlab.univ-nantes.fr/E192263G/m1s2-evoluateddatabases-project/-/blob/main/src/POP_FIVE_HIST_13032023185442226.csv[ici].


- https://stats.oecd.org/Index.aspx?DataSetCode=HISTPOP#[Population par pays par genre par année par tranche d'âge] 
* Licence utilisée
+
Aucune licence prédéfinie clairement sur le site de l'https://www.oecd.org/termsandconditions/[OECD], néanmoins la section "Term of Use" mentionne des conditions d'utilisation similaires à la licence: Creative Commons Attribution 4.0 International License *(CC-BY 4.0)*.
+
*TODO: Effectuer l'attribution tel que décrit dans les règles de l'OECD*
+
[quote,https://www.oecd.org/termsandconditions/]
=====
_"The OECD makes data (the “Data”) *available for use and consultation by the public*.  Data may be subject to restrictions beyond the scope of these Terms and Conditions, either because specific terms apply to those Data or because third parties may have ownership interests. It is the User’s responsibility to verify, either directly in the metadata or, if available, by clicking on the  icon and then referring to the "source" tab, whether the Data is fully or partially owned by third parties and/or whether additional restrictions may apply, and to contact the owner of the Data before incorporating it in your work in order to secure the necessary permissions. The OECD in no way represents or warrants that it owns or controls all rights in all Data, and the OECD will not be liable to any User for any claims brought against the User by third parties in connection with the use of any Data.

*Permitted use*

Except where additional restrictions apply as stated above, *You can extract from, download, copy, adapt, print, distribute, share and embed Data for any purpose, even for commercial use. You must give appropriate credit to the OECD by using the citation associated with the relevant Data, or, if no specific citation is available, You must cite the source information using the following format: OECD (year), (dataset name),(data source) DOI or URL (accessed on (date)).* When sharing or licensing work created using the Data, You agree to include the same acknowledgment requirement in any sub-licenses that You grant, along with the requirement that any further sub-licensees do the same."_

*Terms and Conditions - I. Use of Material - (c) Data - OECD*
=====

