
=== Les 3 datasets utilisés

- https://data.worldbank.org/indicator/EN.ATM.CO2E.PC[Co2 emissions en tonne métrique par pays par année]
* Licence utilisée: The Creative Commons Attribution-NonCommercial 4.0 *(CC BY-NC 4.0)*

* Obtention des fichiers de données
+
Le dataset est téléchargable sous la forme d'un fichier CSV, il est disponible https://gitlab.univ-nantes.fr/E192263G/m1s2-evoluateddatabases-project/-/blob/main/src/API_EN.ATM.CO2E.PC_DS2_en_csv_v2_4902944.csv[ici].

- https://www.kaggle.com/datasets/iamsouravbanerjee/human-development-index-dataset[IDH et GNI par pays par année] 
* Licence utilisée: Creative Commons Attribution 3.0 IGO *(CC BY 3.0 IGO)*

* Obtention des fichiers de données
+
Le dataset est téléchargable sous la forme d'un fichier CSV, il est disponible https://gitlab.univ-nantes.fr/E192263G/m1s2-evoluateddatabases-project/-/blob/main/src/Human%20Development%20Index%20-%20Full.csv[ici].

- http://data.un.org/Data.aspx?d=POP&f=tableCode%3a22[Population par pays par genre par année par tranche d'âge par zone d'habitation] 
* Licence utilisée
+
Aucune licence prédéfinie clairement sur le site http://data.un.org/Host.aspx?Content=UNdataUse[UNdata], néanmoins la section "Term of Use" mentionne des conditions d'utilisation similaires à la licence *CC BY*.
+
[quote,http://data.un.org/Host.aspx?Content=UNdataUse]
=====
_"All data and metadata provided on UNdata’s website are available free of charge and may be copied freely, duplicated and further distributed provided that UNdata is cited as the reference."_ *Term of use - UNdata*
=====

* Obtention des fichiers de données
+
Nous avons rencontré un problème lors de la récupération des données, le dataset faisant approximativement 2 millions de lignes, le site limitant le téléchargement a 100.000 lignes, il était donc impossible de tout télécharger en un seul bloc.
+
Nous avons donc conçu un script bash (https://gitlab.univ-nantes.fr/E192263G/m1s2-evoluateddatabases-project/-/blob/main/scripts/get_data_scripts/population_dataset/download_script.sh[download_script.sh]) permettant de télécharger le dataset au format csv par bloc en le découpant par années.
+
Une fois téléchargé, il ne suffira que d'exécuter le deuxième script bash (https://gitlab.univ-nantes.fr/E192263G/m1s2-evoluateddatabases-project/-/blob/main/scripts/get_data_scripts/population_dataset/conversion_files_script.sh[conversion_files_script.sh]) pour rendre les fichiers utilisables par le programme python.

